// GENERATED by scripts/fetch-contributions.mjs. Do not edit by hand.
// Counts issues and pull requests authored by fabio-rovai in repositories owned
// by other people, excluding closed outreach pull requests. Regenerate with
// `npm run contributions`.

export interface ContributionTotals {
  mergedPullRequests: number;
  openPullRequests: number;
  issuesFiled: number;
  projects: number;
  organisations: number;
  generatedOn: string;
}

export const CONTRIBUTION_TOTALS: ContributionTotals = {
  "mergedPullRequests": 20,
  "openPullRequests": 5,
  "issuesFiled": 42,
  "projects": 26,
  "organisations": 24,
  "generatedOn": "2026-08-25"
};
