// GENERATED by scripts/fetch-repo-stats.mjs. Do not edit by hand.
// Live figures for the Open Ontologies repository. Regenerate with
// `npm run stats`.

export interface RepoStats {
  stars: number;
  forks: number;
  outsideMergedPullRequests: number;
  generatedOn: string;
}

export const OPEN_ONTOLOGIES_STATS: RepoStats = {
  "stars": 456,
  "forks": 59,
  "outsideMergedPullRequests": 20,
  "generatedOn": "2026-08-30"
};
